global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord'

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'https://discord.com/api/webhooks/1504234800771235910/ulJSBsMWOQgOWo65tos4ZRrC8hoq3uj2dx4EGwvwtYQp3ExihGtku7zrVOp66nlExWFw'
    send_resolved: true
